name: Test Workflow

on:
  #push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Install EF Tool
      run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
     
    # Generate migrations bundle
    - name: Build dotnet bundle
      run: |
          cd ./code-first-db-ci-cd
          dotnet ef migrations script -o ${{ github.workspace }}\code-first-db-ci-cd\migration-script.sql --idempotent
          
    # Publish migrations bundle as artifact
    - uses: actions/upload-artifact@v2
      with:
        name: MigrationScript
        path: ${{ github.workspace }}\code-first-db-ci-cd\migration-script.sql
        if-no-files-found: error
        retention-days: 30
        
  deploy-database:
  
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/checkout@v1
    
    - name: Download Build artifacts
      uses: actions/download-artifact@v2
      with:
        name: MigrationScript
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/sql-action@v1
      with:        
        server-name: mitch-sql-test
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        sql-file: migration-script.sql
