name: Test Workflow

on:
  #push:
    #branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Install EF Tool
      run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
     
    # generate migrations bundle
    - name: Build dotnet bundle
      run: |
          cd ./code-first-db-ci-cd
          dotnet ef migrations bundle --configuration github.com.dotnet.efcore.issues.25555
          
   # Publish migrations bundle as artifact
    - uses: actions/upload-artifact@v2
      with:
        name: MigrationBundle
        path: ${{ github.workspace }}\code-first-db-ci-cd\code-first-db-ci-cd\
        if-no-files-found: error
        retention-days: 30
